import type { Manhwa, Comment, Report, AuditLog, User, UserLibraryEntry, ContributorDraft } from './types';

export const INITIAL_USERS: Record<string, User> = {
  guest: {
    id: 'u-guest',
    username: 'Guest_Visitor',
    email: 'guest@neomanhwa.local',
    role: 'guest',
    strike_count: 0,
    mute_expires_at: null,
    is_banned: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    deleted_at: null,
  },
  user: {
    id: 'u-shadow',
    username: 'ShadowMonarch',
    email: 'jinwoo@hunter.kr',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80',
    role: 'user',
    strike_count: 0,
    mute_expires_at: null,
    is_banned: false,
    created_at: '2026-02-15T10:20:00Z',
    updated_at: '2026-03-01T12:00:00Z',
    deleted_at: null,
  },
  contributor: {
    id: 'u-scribe',
    username: 'SeoulScribe',
    email: 'scribe@neomanhwa.org',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80',
    role: 'contributor',
    strike_count: 0,
    mute_expires_at: null,
    is_banned: false,
    created_at: '2026-01-20T08:00:00Z',
    updated_at: '2026-02-10T14:30:00Z',
    deleted_at: null,
  },
  moderator: {
    id: 'u-warden',
    username: 'Gatekeeper_Mod',
    email: 'mod@neomanhwa.org',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&q=80',
    role: 'moderator',
    strike_count: 0,
    mute_expires_at: null,
    is_banned: false,
    created_at: '2025-11-10T09:00:00Z',
    updated_at: '2026-03-20T16:00:00Z',
    deleted_at: null,
  },
  admin: {
    id: 'u-root',
    username: 'Overlord_Admin',
    email: 'admin@neomanhwa.internal',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&q=80',
    role: 'admin',
    strike_count: 0,
    mute_expires_at: null,
    is_banned: false,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
    deleted_at: null,
  },
};

export const INITIAL_USER_LIST: User[] = [
  INITIAL_USERS.user,
  INITIAL_USERS.contributor,
  INITIAL_USERS.moderator,
  INITIAL_USERS.admin,
  {
    id: 'u-troll',
    username: 'SpamBot99',
    email: 'spam@bot.com',
    role: 'user',
    strike_count: 2,
    mute_expires_at: null,
    is_banned: false,
    deletion_requested: true,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    deleted_at: null,
  }
];
import manhwaCatalogRaw from './data/manhwa_500.json';

export const INITIAL_MANHWA: Manhwa[] = (manhwaCatalogRaw as unknown as Manhwa[]).map((item, idx) => ({
  ...item,
  // Ensure backwards compatibility with any hardcoded mock references m-1..m-8
  id: idx === 0 ? '20000000-0000-0000-0000-000000000002' : item.id,
}));

export const INITIAL_LIBRARY: UserLibraryEntry[] = [
  {
    id: 'lib-1',
    user_id: 'u-shadow',
    manhwa_id: 'm-1',
    status: 'reading',
    current_chapter: 54,
    score: 5,
    is_favorite: true,
    updated_at: '2026-10-03T18:40:00Z',
  },
  {
    id: 'lib-2',
    user_id: 'u-shadow',
    manhwa_id: 'm-2',
    status: 'reading',
    current_chapter: 215,
    score: 5,
    is_favorite: true,
    updated_at: '2026-10-02T11:20:00Z',
  },
  {
    id: 'lib-3',
    user_id: 'u-shadow',
    manhwa_id: 'm-3',
    status: 'completed',
    current_chapter: 164,
    score: 5,
    is_favorite: false,
    updated_at: '2026-09-15T09:00:00Z',
  },
  {
    id: 'lib-4',
    user_id: 'u-shadow',
    manhwa_id: 'm-4',
    status: 'on_hold',
    current_chapter: 89,
    score: 4,
    is_favorite: false,
    updated_at: '2026-08-20T14:15:00Z',
  },
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'c-1',
    manhwa_id: 'm-1',
    user_id: 'u-shadow',
    username: 'ShadowMonarch',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80',
    user_role: 'user',
    parent_id: null,
    content: 'Suho wielding both the monarch aura and the dual daggers in chapter 52 was peak cinema. Redice studio never misses with the lighting on shadow extraction!',
    is_spoiler: false,
    upvotes: 42,
    downvotes: 1,
    is_hidden: false,
    created_at: '2026-10-02T19:30:00Z',
    updated_at: '2026-10-02T19:30:00Z',
    deleted_at: null,
  },
  {
    id: 'c-2',
    manhwa_id: 'm-1',
    user_id: 'u-scribe',
    username: 'SeoulScribe',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80',
    user_role: 'contributor',
    parent_id: 'c-1',
    content: 'Agreed, and notice how they adapted the light novel chapter 88 slightly differently to pace the outer god lore better for webtoon readers.',
    is_spoiler: false,
    upvotes: 15,
    downvotes: 0,
    is_hidden: false,
    created_at: '2026-10-02T20:15:00Z',
    updated_at: '2026-10-02T20:15:00Z',
    deleted_at: null,
  },
  {
    id: 'c-3',
    manhwa_id: 'm-1',
    user_id: 'u-hunter99',
    username: 'DungeonRunner',
    user_role: 'user',
    parent_id: null,
    content: 'MAJOR SPOILER: Beware, the Grand Priest of the Itarim turns out to be an undercover vessel of the Absolute Being!',
    is_spoiler: true,
    upvotes: 8,
    downvotes: 14,
    is_hidden: false,
    created_at: '2026-10-03T02:40:00Z',
    updated_at: '2026-10-03T02:40:00Z',
    deleted_at: null,
  },
  {
    id: 'c-4',
    manhwa_id: 'm-2',
    user_id: 'u-scribe',
    username: 'SeoulScribe',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80',
    user_role: 'contributor',
    parent_id: null,
    content: 'The 73rd Demon King arc adaptation is unmatched. Kim Dokja’s sacrifice sequence emotionally wrecked me. Five stars without hesitation.',
    is_spoiler: true,
    upvotes: 89,
    downvotes: 2,
    is_hidden: false,
    created_at: '2026-09-29T14:10:00Z',
    updated_at: '2026-09-29T14:10:00Z',
    deleted_at: null,
  },
  {
    id: 'c-5',
    manhwa_id: 'm-3',
    user_id: 'u-shadow',
    username: 'ShadowMonarch',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80',
    user_role: 'user',
    parent_id: null,
    content: 'Lloyd’s facial expressions alone carry this series to legendary status. Javier’s silent suffering next to him is comedy gold.',
    is_spoiler: false,
    upvotes: 114,
    downvotes: 0,
    is_hidden: false,
    created_at: '2026-10-01T12:00:00Z',
    updated_at: '2026-10-01T12:00:00Z',
    deleted_at: null,
  }
];

export const INITIAL_REPORTS: Report[] = [
  {
    id: 'rep-1',
    reporter_id: 'u-shadow',
    reporter_name: 'ShadowMonarch',
    target_type: 'comment',
    target_id: 'c-3',
    target_preview: 'MAJOR SPOILER: Beware, the Grand Priest of the Itarim turns out...',
    reason: 'spoilers',
    details: 'User posted an untagged ending spoiler in early chapter discussion thread.',
    status: 'pending',
    resolved_by: null,
    created_at: '2026-10-03T03:00:00Z',
    resolved_at: null,
  },
  {
    id: 'rep-2',
    reporter_id: 'u-hunter99',
    reporter_name: 'DungeonRunner',
    target_type: 'manhwa',
    target_id: 'm-3',
    target_preview: 'The Greatest Estate Developer',
    reason: 'incorrect_data',
    details: 'Release year listed as 2021, but web novel adaptation began late 2020.',
    status: 'pending',
    resolved_by: null,
    created_at: '2026-10-01T18:22:00Z',
    resolved_at: null,
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-101',
    actor_id: 'u-root',
    actor_name: 'Overlord_Admin',
    actor_role: 'admin',
    action: 'ROLE_PROMOTION',
    target_entity: 'User',
    target_id: 'u-warden',
    changes: { role: { old: 'contributor', new: 'moderator' } },
    ip_address: '192.168.1.100',
    timestamp: '2026-10-01T08:14:22Z',
  },
  {
    id: 'log-102',
    actor_id: 'u-warden',
    actor_name: 'Gatekeeper_Mod',
    actor_role: 'moderator',
    action: 'COMMENT_FLAG_HIDE',
    target_entity: 'Comment',
    target_id: 'c-99',
    changes: { is_hidden: { old: false, new: true } },
    ip_address: '192.168.1.144',
    timestamp: '2026-10-02T11:45:10Z',
  },
  {
    id: 'log-103',
    actor_id: 'u-root',
    actor_name: 'Overlord_Admin',
    actor_role: 'admin',
    action: 'MANHWA_METADATA_UPDATE',
    target_entity: 'Manhwa',
    target_id: 'm-1',
    changes: { total_chapters: { old: 56, new: 58 } },
    ip_address: '192.168.1.100',
    timestamp: '2026-10-03T09:00:00Z',
  }
];

export const INITIAL_CONTRIBUTOR_DRAFTS: ContributorDraft[] = [
  {
    id: 'draft-1',
    contributor_id: 'u-scribe',
    contributor_name: 'SeoulScribe',
    title: 'Murim Login',
    hangul: '로그인 무림',
    format: 'manhwa',
    status: 'ongoing',
    synopsis: 'Jin Taekyung is a low-rank hunter in a monster-infested Seoul who accidentally discovers a hyper-realistic VR capsule that connects him directly into a brutal Murim realm.',
    genres: ['Murim', 'Action', 'Comedy', 'Level Up'],
    total_chapters: 190,
    submission_date: '2026-10-02T16:00:00Z',
    moderation_status: 'pending',
  }
];
